services:
  whatsapp-bot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-whatsapp-nest-app
    restart: always
    ports:
      - "${PORT}:${PORT}" # Usa el puerto del .env
    volumes:
      # Usa el nombre de la carpeta del .env para mapear el volumen
      - ./${AUTH_FOLDER_NAME}:/app/${AUTH_FOLDER_NAME}
    environment:
      - PORT=${PORT}
      - NODE_ENV=production # Aquí lo forzamos a producción dentro del contenedor
      - TZ=${TZ}