services:
  whatsapp-bot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-nest:latest
    container_name: chat-whatsapp-nest-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      # Solo mapeamos las credenciales para NO perder el QR
      - ./${AUTH_FOLDER_NAME}:/app/${AUTH_FOLDER_NAME}
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - TZ=${TZ}
      - AUTH_FOLDER_NAME=${AUTH_FOLDER_NAME}